version: "3.1"
services:
  db:
    container_name: sqlnode-postgres
    image: postgres:10-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ecommerce
  admin:
    container_name: sqlnode-adminer
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080
